### ISSUE TITLE
broken tokens 

### ISSUE THREAD

**Issue by VasiliyBogdanovichROC** [standy/ts-date#18]
cannot use tokens properly (even from examples)
v3.0.1
<img width="954" alt="Screen Shot 2022-08-04 at 13 42 18" src="https://user-images.githubusercontent.com/79999595/182828269-ae843668-e290-4094-baa7-b88047e1156b.png">

**Comment by standy** [comment]
Should import particular language:

```
import { format } from "ts-date/esm/locale/en";
```

While library still usable without language, format and parse will not work for lang-dependent features
