### ISSUE TITLE
parse('290220', 'DDMMYY') returns wrong date March 1st 2020 (Leap Year)

### ISSUE THREAD

**Issue by NillDk** [standy/ts-date#5]
I need to parse dates in the format 'DDMMYY'.
It works fine, unless it is Februrary 29th in a leap year.
E.g.: parse('290220', 'DDMMYY')

Expected result: Februrary 29th 2020
Actual result: March 1st 2020

**Comment by standy** [comment]
Nice catch with leap year, thank you! 
Update coming

The reason is that parser goes from left to right adding values to result date, like:
```
start with 1970-01-01
DD 29 => 1970-01-29
MM 02 => 1970-02-29 (1970-03-01)
YY 20 => 2020-03-01
```
