### ISSUE TITLE
Should parse('400120', 'DDMMYY') return null or a date?

### ISSUE THREAD

**Issue by NillDk** [standy/ts-date#6]
parse('400120', 'DDMMYY')

Expected result: null
Actual result: January 9th 2020

Is this correct behavior?

**Comment by standy** [comment]
Yes, result should be null, but for performance reasons I skip checking result in parser (but not in parseIso). Please don't rely on current behavior, may be changed in future

If you need to be sure that parsed date is correct, you can use method like this:
```
function parseWithResultCheck(input, template) {
  const d = parse(input, template);
  if (format(d, template) === input) return d;
  return null;
}
```

**Comment by NillDk** [comment]
I thought it might be for performance reasons and made something like you suggested.
Thank you for the detailed feed back :)
